apiVersion: v2
name: techtrends
description: A Helm chart for deploying the TechTrends application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - techtrends
maintainers:
  - name: Nourhan Mohammed
    email: nourhan@example.com
